name: Tests

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.9", "3.10"]
        session:
          - "test"
        include:
          - os: "ubuntu-latest"
            python-version: "3.10"
            session: "extras"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U nox

      - name: Run tests
        run: |
          python -m nox --non-interactive --error-on-missing-interpreter \
            --session ${{ matrix.session }}-${{ matrix.python-version }}
